-- MySQL Script generated by MySQL Workbench
-- Tue Oct 19 20:44:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bancoaps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancoaps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancoaps` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bancoaps` ;

-- -----------------------------------------------------
-- Table `bancoaps`.`dono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoaps`.`dono` (
  `nome` VARCHAR(80) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NULL,
  `endereco` VARCHAR(50) NULL DEFAULT NULL,
  `idDono` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idDono`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancoaps`.`biometria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoaps`.`biometria` (
  `biometria` longblob NOT NULL,
  `Validacao` INT NOT NULL AUTO_INCREMENT,
  `idFuncionario` INT NULL DEFAULT NULL,
  INDEX `idFuncionario_idx` (`idFuncionario` ASC) VISIBLE,
  PRIMARY KEY (`Validacao`),
  CONSTRAINT `idFuncionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `bancoaps`.`funcionario` (`idFuncionario`)
    ON DELETE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
-- -----------------------------------------------------
-- Table `bancoaps`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoaps`.`funcionario` (
  `nome` VARCHAR(80) NULL DEFAULT NULL,
  `cpf` VARCHAR(20) NULL DEFAULT NULL,
  `nivelAcesso` int NULL DEFAULT NULL,
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancoaps`.`agrotoxico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancoaps`.`agrotoxico` (
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` VARCHAR(30)  NULL DEFAULT NULL,
  `status` INT NULL DEFAULT NULL,
  `idDono` INT NULL,
  `idAgrotoxico` INT NOT NULL AUTO_INCREMENT,
  INDEX `idDono_idx` (`idDono` ASC) VISIBLE,
  PRIMARY KEY (`idAgrotoxico`),
  CONSTRAINT `idDono`
    FOREIGN KEY (`idDono`)
    REFERENCES `bancoaps`.`dono` (`idDono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `bancoaps`.`login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(80) NULL DEFAULT NULL,
  `senha` VARCHAR(30)  NULL DEFAULT NULL,
  `idDono` INT NULL,
  PRIMARY KEY (`idLogin`),
    FOREIGN KEY (`idDono`)
    REFERENCES `bancoaps`.`dono` (`idDono`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;